//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdvansTimbrado
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:advanswsdl", ConfigurationName="AdvansTimbrado.advanswsdlPortType")]
    public interface advanswsdlPortType
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:advanswsdl#timbrar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<AdvansTimbrado.RespuestaTimbre> timbrarAsync(string credential, string cfdi);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:advanswsdl#validar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<AdvansTimbrado.RespuestaValidacion> validarAsync(string credential, string cfdi);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:advanswsdl#timbrarRetencion", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<AdvansTimbrado.RespuestaTimbre> timbrarRetencionAsync(string credential, string xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:advanswsdl#timbrar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<AdvansTimbrado.RespuestaTimbre2> timbrar2Async(string credential, string cfdi);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:advanswsdl#timbrarRetencion2", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<AdvansTimbrado.RespuestaTimbre2> timbrarRetencion2Async(string credential, string xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:advanswsdl#timbrar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<AdvansTimbrado.RespuestaTimbre> timbrar3Async(string credential, string cfdi);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:advanswsdl#timbrar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<AdvansTimbrado.RespuestaTimbre4> timbrar4Async(string credential, string cfdi);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:advanswsdl#cancelar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<AdvansTimbrado.RespuestaCancelacion> cancelarAsync(string credential, string rfc_emisor, string uuid, string motivo, string folio_sustitucion, string key, string cer);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:advanswsdl#cancelarRetencion", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<AdvansTimbrado.RespuestaCancelacion> cancelarRetencionAsync(string credential, string rfc_emisor, string uuid, string motivo, string folio_sustitucion, string key, string cer);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:advanswsdl#cancelarPFXSync", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<AdvansTimbrado.RespuestaCancelacion> cancelarPFXSyncAsync(string credential, string rfc_emisor, string uuid, string motivo, string folio_sustitucion, string pfx, string pfx_password);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:advanswsdl#consulta", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<AdvansTimbrado.RespuestaConsulta> consultarAsync(string credential, string uuid);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:advanswsdl#consulta", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<AdvansTimbrado.RespuestaConsulta> consultar_cfdiAsync(string credential, string uuid);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:advanswsdl#consultaHora", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<AdvansTimbrado.RespuestaConsultaHora> consultar_horaAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:advanswsdl#ValidarCertificado", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<AdvansTimbrado.RespuestaValidarCertificado> validar_certificadoAsync(string credential, string cer);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:advanswsdl#ValidarCertificado", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<AdvansTimbrado.RespuestaValidarCertificado> confirmacionAsync(string credential, string emisor_rfc, string receptor_rfc, string email);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:advanswsdl")]
    public partial class RespuestaTimbre
    {
        
        private string codeField;
        
        private string subCodeField;
        
        private string messageField;
        
        private string timbreField;
        
        /// <remarks/>
        public string Code
        {
            get
            {
                return this.codeField;
            }
            set
            {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        public string SubCode
        {
            get
            {
                return this.subCodeField;
            }
            set
            {
                this.subCodeField = value;
            }
        }
        
        /// <remarks/>
        public string Message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        public string Timbre
        {
            get
            {
                return this.timbreField;
            }
            set
            {
                this.timbreField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:advanswsdl")]
    public partial class RespuestaValidarCertificado
    {
        
        private string codeField;
        
        private string subCodeField;
        
        private string idField;
        
        private string messageField;
        
        /// <remarks/>
        public string Code
        {
            get
            {
                return this.codeField;
            }
            set
            {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        public string SubCode
        {
            get
            {
                return this.subCodeField;
            }
            set
            {
                this.subCodeField = value;
            }
        }
        
        /// <remarks/>
        public string ID
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string Message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:advanswsdl")]
    public partial class RespuestaConsultaHora
    {
        
        private string horaField;
        
        /// <remarks/>
        public string Hora
        {
            get
            {
                return this.horaField;
            }
            set
            {
                this.horaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:advanswsdl")]
    public partial class RespuestaConsulta
    {
        
        private string codeField;
        
        private string subCodeField;
        
        private string messageField;
        
        private string acuseField;
        
        /// <remarks/>
        public string Code
        {
            get
            {
                return this.codeField;
            }
            set
            {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        public string SubCode
        {
            get
            {
                return this.subCodeField;
            }
            set
            {
                this.subCodeField = value;
            }
        }
        
        /// <remarks/>
        public string Message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        public string Acuse
        {
            get
            {
                return this.acuseField;
            }
            set
            {
                this.acuseField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:advanswsdl")]
    public partial class RespuestaCancelacion
    {
        
        private string codeField;
        
        private string subCodeField;
        
        private string messageField;
        
        private string acuseField;
        
        /// <remarks/>
        public string Code
        {
            get
            {
                return this.codeField;
            }
            set
            {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        public string SubCode
        {
            get
            {
                return this.subCodeField;
            }
            set
            {
                this.subCodeField = value;
            }
        }
        
        /// <remarks/>
        public string Message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        public string Acuse
        {
            get
            {
                return this.acuseField;
            }
            set
            {
                this.acuseField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:advanswsdl")]
    public partial class RespuestaTimbre4
    {
        
        private string codeField;
        
        private string subCodeField;
        
        private string messageField;
        
        private string cFDIField;
        
        private string cOTFDField;
        
        /// <remarks/>
        public string Code
        {
            get
            {
                return this.codeField;
            }
            set
            {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        public string SubCode
        {
            get
            {
                return this.subCodeField;
            }
            set
            {
                this.subCodeField = value;
            }
        }
        
        /// <remarks/>
        public string Message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        public string CFDI
        {
            get
            {
                return this.cFDIField;
            }
            set
            {
                this.cFDIField = value;
            }
        }
        
        /// <remarks/>
        public string COTFD
        {
            get
            {
                return this.cOTFDField;
            }
            set
            {
                this.cOTFDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:advanswsdl")]
    public partial class RespuestaTimbre2
    {
        
        private string codeField;
        
        private string subCodeField;
        
        private string messageField;
        
        private string cFDIField;
        
        /// <remarks/>
        public string Code
        {
            get
            {
                return this.codeField;
            }
            set
            {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        public string SubCode
        {
            get
            {
                return this.subCodeField;
            }
            set
            {
                this.subCodeField = value;
            }
        }
        
        /// <remarks/>
        public string Message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        public string CFDI
        {
            get
            {
                return this.cFDIField;
            }
            set
            {
                this.cFDIField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:advanswsdl")]
    public partial class RespuestaValidacion
    {
        
        private string codeField;
        
        private string subCodeField;
        
        private string messageField;
        
        private bool validField;
        
        private string resultField;
        
        /// <remarks/>
        public string Code
        {
            get
            {
                return this.codeField;
            }
            set
            {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        public string SubCode
        {
            get
            {
                return this.subCodeField;
            }
            set
            {
                this.subCodeField = value;
            }
        }
        
        /// <remarks/>
        public string Message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        public bool Valid
        {
            get
            {
                return this.validField;
            }
            set
            {
                this.validField = value;
            }
        }
        
        /// <remarks/>
        public string Result
        {
            get
            {
                return this.resultField;
            }
            set
            {
                this.resultField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public interface advanswsdlPortTypeChannel : AdvansTimbrado.advanswsdlPortType, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public partial class advanswsdlPortTypeClient : System.ServiceModel.ClientBase<AdvansTimbrado.advanswsdlPortType>, AdvansTimbrado.advanswsdlPortType
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public advanswsdlPortTypeClient() : 
                base(advanswsdlPortTypeClient.GetDefaultBinding(), advanswsdlPortTypeClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.advanswsdlPort.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public advanswsdlPortTypeClient(EndpointConfiguration endpointConfiguration) : 
                base(advanswsdlPortTypeClient.GetBindingForEndpoint(endpointConfiguration), advanswsdlPortTypeClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public advanswsdlPortTypeClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(advanswsdlPortTypeClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public advanswsdlPortTypeClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(advanswsdlPortTypeClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public advanswsdlPortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<AdvansTimbrado.RespuestaTimbre> timbrarAsync(string credential, string cfdi)
        {
            return base.Channel.timbrarAsync(credential, cfdi);
        }
        
        public System.Threading.Tasks.Task<AdvansTimbrado.RespuestaValidacion> validarAsync(string credential, string cfdi)
        {
            return base.Channel.validarAsync(credential, cfdi);
        }
        
        public System.Threading.Tasks.Task<AdvansTimbrado.RespuestaTimbre> timbrarRetencionAsync(string credential, string xml)
        {
            return base.Channel.timbrarRetencionAsync(credential, xml);
        }
        
        public System.Threading.Tasks.Task<AdvansTimbrado.RespuestaTimbre2> timbrar2Async(string credential, string cfdi)
        {
            return base.Channel.timbrar2Async(credential, cfdi);
        }
        
        public System.Threading.Tasks.Task<AdvansTimbrado.RespuestaTimbre2> timbrarRetencion2Async(string credential, string xml)
        {
            return base.Channel.timbrarRetencion2Async(credential, xml);
        }
        
        public System.Threading.Tasks.Task<AdvansTimbrado.RespuestaTimbre> timbrar3Async(string credential, string cfdi)
        {
            return base.Channel.timbrar3Async(credential, cfdi);
        }
        
        public System.Threading.Tasks.Task<AdvansTimbrado.RespuestaTimbre4> timbrar4Async(string credential, string cfdi)
        {
            return base.Channel.timbrar4Async(credential, cfdi);
        }
        
        public System.Threading.Tasks.Task<AdvansTimbrado.RespuestaCancelacion> cancelarAsync(string credential, string rfc_emisor, string uuid, string motivo, string folio_sustitucion, string key, string cer)
        {
            return base.Channel.cancelarAsync(credential, rfc_emisor, uuid, motivo, folio_sustitucion, key, cer);
        }
        
        public System.Threading.Tasks.Task<AdvansTimbrado.RespuestaCancelacion> cancelarRetencionAsync(string credential, string rfc_emisor, string uuid, string motivo, string folio_sustitucion, string key, string cer)
        {
            return base.Channel.cancelarRetencionAsync(credential, rfc_emisor, uuid, motivo, folio_sustitucion, key, cer);
        }
        
        public System.Threading.Tasks.Task<AdvansTimbrado.RespuestaCancelacion> cancelarPFXSyncAsync(string credential, string rfc_emisor, string uuid, string motivo, string folio_sustitucion, string pfx, string pfx_password)
        {
            return base.Channel.cancelarPFXSyncAsync(credential, rfc_emisor, uuid, motivo, folio_sustitucion, pfx, pfx_password);
        }
        
        public System.Threading.Tasks.Task<AdvansTimbrado.RespuestaConsulta> consultarAsync(string credential, string uuid)
        {
            return base.Channel.consultarAsync(credential, uuid);
        }
        
        public System.Threading.Tasks.Task<AdvansTimbrado.RespuestaConsulta> consultar_cfdiAsync(string credential, string uuid)
        {
            return base.Channel.consultar_cfdiAsync(credential, uuid);
        }
        
        public System.Threading.Tasks.Task<AdvansTimbrado.RespuestaConsultaHora> consultar_horaAsync()
        {
            return base.Channel.consultar_horaAsync();
        }
        
        public System.Threading.Tasks.Task<AdvansTimbrado.RespuestaValidarCertificado> validar_certificadoAsync(string credential, string cer)
        {
            return base.Channel.validar_certificadoAsync(credential, cer);
        }
        
        public System.Threading.Tasks.Task<AdvansTimbrado.RespuestaValidarCertificado> confirmacionAsync(string credential, string emisor_rfc, string receptor_rfc, string email)
        {
            return base.Channel.confirmacionAsync(credential, emisor_rfc, receptor_rfc, email);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.advanswsdlPort))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.advanswsdlPort))
            {
                return new System.ServiceModel.EndpointAddress("https://ws40.advans.mx/ws/awscfdi.php");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return advanswsdlPortTypeClient.GetBindingForEndpoint(EndpointConfiguration.advanswsdlPort);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return advanswsdlPortTypeClient.GetEndpointAddress(EndpointConfiguration.advanswsdlPort);
        }
        
        public enum EndpointConfiguration
        {
            
            advanswsdlPort,
        }
    }
}
