//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CancearAdvansWS
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.ServiceContractAttribute(Name="advans-cfdi-cancelacionPortType", Namespace="urn:advans-cfdi-cancelacion", ConfigurationName="CancearAdvansWS.advanscfdicancelacionPortType")]
    public interface advanscfdicancelacionPortType
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:advans-cfdi-cancelacion#ConsultarEstado", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="ConsultarEstadoResponse")]
        CancearAdvansWS.ConsultarEstadoResponse ConsultarEstado(CancearAdvansWS.ConsultarEstadoRequest ConsultarEstadoRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:advans-cfdi-cancelacion#ConsultarEstado", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="ConsultarEstadoResponse")]
        System.Threading.Tasks.Task<CancearAdvansWS.ConsultarEstadoResponse> ConsultarEstadoAsync(CancearAdvansWS.ConsultarEstadoRequest ConsultarEstadoRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:advans-cfdi-cancelacion#Cancelar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="CancelarResponse")]
        CancearAdvansWS.CancelarResponse Cancelar(CancearAdvansWS.CancelarRequest CancelarRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:advans-cfdi-cancelacion#Cancelar", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="CancelarResponse")]
        System.Threading.Tasks.Task<CancearAdvansWS.CancelarResponse> CancelarAsync(CancearAdvansWS.CancelarRequest CancelarRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:advans-cfdi-cancelacion#AutorizarCancelacionAutofirma", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="SimpleResponse")]
        CancearAdvansWS.SimpleResponse AutorizarCancelacionAutofirma(CancearAdvansWS.AutorizarCancelacionAutofirmaRequest AutorizarCancelacionAutofirmaRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:advans-cfdi-cancelacion#AutorizarCancelacionAutofirma", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="SimpleResponse")]
        System.Threading.Tasks.Task<CancearAdvansWS.SimpleResponse> AutorizarCancelacionAutofirmaAsync(CancearAdvansWS.AutorizarCancelacionAutofirmaRequest AutorizarCancelacionAutofirmaRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:advans-cfdi-cancelacion#ConsultarDocumentosRelacionados", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="ConsultarDocumentosRelacionadosResponse")]
        CancearAdvansWS.ConsultarDocumentosRelacionadosResponse ConsultarDocumentosRelacionados(CancearAdvansWS.ConsultarDocumentosRelacionadosRequest ConsultarDocumentosRelacionadosRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:advans-cfdi-cancelacion#ConsultarDocumentosRelacionados", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="ConsultarDocumentosRelacionadosResponse")]
        System.Threading.Tasks.Task<CancearAdvansWS.ConsultarDocumentosRelacionadosResponse> ConsultarDocumentosRelacionadosAsync(CancearAdvansWS.ConsultarDocumentosRelacionadosRequest ConsultarDocumentosRelacionadosRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:advans-cfdi-cancelacion#CancelarAutofirma", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="CancelarResponse")]
        CancearAdvansWS.CancelarResponse CancelarAutofirma(CancearAdvansWS.CancelarAutofirmaRequest CancelarAutofirmaRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:advans-cfdi-cancelacion#CancelarAutofirma", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="CancelarResponse")]
        System.Threading.Tasks.Task<CancearAdvansWS.CancelarResponse> CancelarAutofirmaAsync(CancearAdvansWS.CancelarAutofirmaRequest CancelarAutofirmaRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:advans-cfdi-cancelacion#ConsultarDocumentosRelacionadosAutofirma", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="ConsultarDocumentosRelacionadosResponse")]
        CancearAdvansWS.ConsultarDocumentosRelacionadosResponse ConsultarDocumentosRelacionadosAutofirma(CancearAdvansWS.ConsultarDocumentosRelacionadosAutofirmaRequest ConsultarDocumentosRelacionadosAutofirmaRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:advans-cfdi-cancelacion#ConsultarDocumentosRelacionadosAutofirma", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="ConsultarDocumentosRelacionadosResponse")]
        System.Threading.Tasks.Task<CancearAdvansWS.ConsultarDocumentosRelacionadosResponse> ConsultarDocumentosRelacionadosAutofirmaAsync(CancearAdvansWS.ConsultarDocumentosRelacionadosAutofirmaRequest ConsultarDocumentosRelacionadosAutofirmaRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:advans-cfdi-cancelacion#ConsultarAutorizacionesPendientesAutofirma", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="ConsultarAutorizacionesPendientesResponse")]
        CancearAdvansWS.ConsultarAutorizacionesPendientesResponse ConsultarAutorizacionesPendientesAutofirma(CancearAdvansWS.RFCEmisorRequest RFCEmisorRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:advans-cfdi-cancelacion#ConsultarAutorizacionesPendientesAutofirma", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="ConsultarAutorizacionesPendientesResponse")]
        System.Threading.Tasks.Task<CancearAdvansWS.ConsultarAutorizacionesPendientesResponse> ConsultarAutorizacionesPendientesAutofirmaAsync(CancearAdvansWS.RFCEmisorRequest RFCEmisorRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:advans-cfdi-cancelacion#ConsultarEstadoSAT", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="ConsultarEstadoSATResponse")]
        CancearAdvansWS.ConsultarEstadoSATResponse ConsultarEstadoSAT(CancearAdvansWS.ConsultarEstadoSATRequest ConsultarEstadoSATRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:advans-cfdi-cancelacion#ConsultarEstadoSAT", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="ConsultarEstadoSATResponse")]
        System.Threading.Tasks.Task<CancearAdvansWS.ConsultarEstadoSATResponse> ConsultarEstadoSATAsync(CancearAdvansWS.ConsultarEstadoSATRequest ConsultarEstadoSATRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:advans-cfdi-cancelacion#ConsultarEstadoSolicitud", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="ConsultarEstadoSolicitudResponse")]
        CancearAdvansWS.ConsultarEstadoSolicitudResponse ConsultarEstadoSolicitud(CancearAdvansWS.ConsultarEstadoSolicitudRequest ConsultarEstadoSolicitudRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:advans-cfdi-cancelacion#ConsultarEstadoSolicitud", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="ConsultarEstadoSolicitudResponse")]
        System.Threading.Tasks.Task<CancearAdvansWS.ConsultarEstadoSolicitudResponse> ConsultarEstadoSolicitudAsync(CancearAdvansWS.ConsultarEstadoSolicitudRequest ConsultarEstadoSolicitudRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:advans-cfdi-cancelacion#AutorizarCancelacion", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="SimpleResponse")]
        CancearAdvansWS.SimpleResponse AutorizarCancelacion(CancearAdvansWS.AutorizarCancelacionRequest AutorizarCancelacionRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:advans-cfdi-cancelacion#AutorizarCancelacion", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="SimpleResponse")]
        System.Threading.Tasks.Task<CancearAdvansWS.SimpleResponse> AutorizarCancelacionAsync(CancearAdvansWS.AutorizarCancelacionRequest AutorizarCancelacionRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:advans-cfdi-cancelacion#ConsultarAutorizacionesPendientes", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="ConsultarAutorizacionesPendientesResponse")]
        CancearAdvansWS.ConsultarAutorizacionesPendientesResponse ConsultarAutorizacionesPendientes(CancearAdvansWS.SimpleKeysRequest SimpleKeysRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:advans-cfdi-cancelacion#ConsultarAutorizacionesPendientes", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="ConsultarAutorizacionesPendientesResponse")]
        System.Threading.Tasks.Task<CancearAdvansWS.ConsultarAutorizacionesPendientesResponse> ConsultarAutorizacionesPendientesAsync(CancearAdvansWS.SimpleKeysRequest SimpleKeysRequest);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:advans-cfdi-cancelacion")]
    public partial class ConsultarEstadoRequest : object, System.ComponentModel.INotifyPropertyChanged
    {
        
        private string idField;
        
        /// <remarks/>
        public string Id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
                this.RaisePropertyChanged("Id");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:advans-cfdi-cancelacion")]
    public partial class SimpleKeysRequest : object, System.ComponentModel.INotifyPropertyChanged
    {
        
        private string privateKeyPemField;
        
        private string publicKeyPemField;
        
        /// <remarks/>
        public string PrivateKeyPem
        {
            get
            {
                return this.privateKeyPemField;
            }
            set
            {
                this.privateKeyPemField = value;
                this.RaisePropertyChanged("PrivateKeyPem");
            }
        }
        
        /// <remarks/>
        public string PublicKeyPem
        {
            get
            {
                return this.publicKeyPemField;
            }
            set
            {
                this.publicKeyPemField = value;
                this.RaisePropertyChanged("PublicKeyPem");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:advans-cfdi-cancelacion")]
    public partial class AutorizarCancelacionRequest : object, System.ComponentModel.INotifyPropertyChanged
    {
        
        private string privateKeyPemField;
        
        private string publicKeyPemField;
        
        private string uuidField;
        
        private string respuestaField;
        
        /// <remarks/>
        public string PrivateKeyPem
        {
            get
            {
                return this.privateKeyPemField;
            }
            set
            {
                this.privateKeyPemField = value;
                this.RaisePropertyChanged("PrivateKeyPem");
            }
        }
        
        /// <remarks/>
        public string PublicKeyPem
        {
            get
            {
                return this.publicKeyPemField;
            }
            set
            {
                this.publicKeyPemField = value;
                this.RaisePropertyChanged("PublicKeyPem");
            }
        }
        
        /// <remarks/>
        public string Uuid
        {
            get
            {
                return this.uuidField;
            }
            set
            {
                this.uuidField = value;
                this.RaisePropertyChanged("Uuid");
            }
        }
        
        /// <remarks/>
        public string Respuesta
        {
            get
            {
                return this.respuestaField;
            }
            set
            {
                this.respuestaField = value;
                this.RaisePropertyChanged("Respuesta");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:advans-cfdi-cancelacion")]
    public partial class ConsultarEstadoSolicitudResponse : object, System.ComponentModel.INotifyPropertyChanged
    {
        
        private int codeField;
        
        private string messageField;
        
        private string detailField;
        
        private string acuseSATField;
        
        /// <remarks/>
        public int Code
        {
            get
            {
                return this.codeField;
            }
            set
            {
                this.codeField = value;
                this.RaisePropertyChanged("Code");
            }
        }
        
        /// <remarks/>
        public string Message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
                this.RaisePropertyChanged("Message");
            }
        }
        
        /// <remarks/>
        public string Detail
        {
            get
            {
                return this.detailField;
            }
            set
            {
                this.detailField = value;
                this.RaisePropertyChanged("Detail");
            }
        }
        
        /// <remarks/>
        public string AcuseSAT
        {
            get
            {
                return this.acuseSATField;
            }
            set
            {
                this.acuseSATField = value;
                this.RaisePropertyChanged("AcuseSAT");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:advans-cfdi-cancelacion")]
    public partial class ConsultarEstadoSolicitudRequest : object, System.ComponentModel.INotifyPropertyChanged
    {
        
        private string idField;
        
        /// <remarks/>
        public string Id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
                this.RaisePropertyChanged("Id");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:advans-cfdi-cancelacion")]
    public partial class ConsultarEstadoSATResponse : object, System.ComponentModel.INotifyPropertyChanged
    {
        
        private string codigoEstatusField;
        
        private string esCancelableField;
        
        private string estadoField;
        
        private string estatusCancelacionField;
        
        /// <remarks/>
        public string CodigoEstatus
        {
            get
            {
                return this.codigoEstatusField;
            }
            set
            {
                this.codigoEstatusField = value;
                this.RaisePropertyChanged("CodigoEstatus");
            }
        }
        
        /// <remarks/>
        public string EsCancelable
        {
            get
            {
                return this.esCancelableField;
            }
            set
            {
                this.esCancelableField = value;
                this.RaisePropertyChanged("EsCancelable");
            }
        }
        
        /// <remarks/>
        public string Estado
        {
            get
            {
                return this.estadoField;
            }
            set
            {
                this.estadoField = value;
                this.RaisePropertyChanged("Estado");
            }
        }
        
        /// <remarks/>
        public string EstatusCancelacion
        {
            get
            {
                return this.estatusCancelacionField;
            }
            set
            {
                this.estatusCancelacionField = value;
                this.RaisePropertyChanged("EstatusCancelacion");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:advans-cfdi-cancelacion")]
    public partial class ConsultarEstadoSATRequest : object, System.ComponentModel.INotifyPropertyChanged
    {
        
        private string uuidField;
        
        private string rfcEmisorField;
        
        private string rfcReceptorField;
        
        private double totalField;
        
        /// <remarks/>
        public string Uuid
        {
            get
            {
                return this.uuidField;
            }
            set
            {
                this.uuidField = value;
                this.RaisePropertyChanged("Uuid");
            }
        }
        
        /// <remarks/>
        public string RfcEmisor
        {
            get
            {
                return this.rfcEmisorField;
            }
            set
            {
                this.rfcEmisorField = value;
                this.RaisePropertyChanged("RfcEmisor");
            }
        }
        
        /// <remarks/>
        public string RfcReceptor
        {
            get
            {
                return this.rfcReceptorField;
            }
            set
            {
                this.rfcReceptorField = value;
                this.RaisePropertyChanged("RfcReceptor");
            }
        }
        
        /// <remarks/>
        public double Total
        {
            get
            {
                return this.totalField;
            }
            set
            {
                this.totalField = value;
                this.RaisePropertyChanged("Total");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:advans-cfdi-cancelacion")]
    public partial class ConsultarAutorizacionesPendientesResponse : object, System.ComponentModel.INotifyPropertyChanged
    {
        
        private int codeField;
        
        private string messageField;
        
        private string listaFoliosField;
        
        /// <remarks/>
        public int Code
        {
            get
            {
                return this.codeField;
            }
            set
            {
                this.codeField = value;
                this.RaisePropertyChanged("Code");
            }
        }
        
        /// <remarks/>
        public string Message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
                this.RaisePropertyChanged("Message");
            }
        }
        
        /// <remarks/>
        public string ListaFolios
        {
            get
            {
                return this.listaFoliosField;
            }
            set
            {
                this.listaFoliosField = value;
                this.RaisePropertyChanged("ListaFolios");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:advans-cfdi-cancelacion")]
    public partial class RFCEmisorRequest : object, System.ComponentModel.INotifyPropertyChanged
    {
        
        private string rfcEmisorField;
        
        /// <remarks/>
        public string RfcEmisor
        {
            get
            {
                return this.rfcEmisorField;
            }
            set
            {
                this.rfcEmisorField = value;
                this.RaisePropertyChanged("RfcEmisor");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:advans-cfdi-cancelacion")]
    public partial class ConsultarDocumentosRelacionadosAutofirmaRequest : object, System.ComponentModel.INotifyPropertyChanged
    {
        
        private string uuidField;
        
        private string rfcEmisorField;
        
        private string rfcReceptorField;
        
        /// <remarks/>
        public string Uuid
        {
            get
            {
                return this.uuidField;
            }
            set
            {
                this.uuidField = value;
                this.RaisePropertyChanged("Uuid");
            }
        }
        
        /// <remarks/>
        public string RfcEmisor
        {
            get
            {
                return this.rfcEmisorField;
            }
            set
            {
                this.rfcEmisorField = value;
                this.RaisePropertyChanged("RfcEmisor");
            }
        }
        
        /// <remarks/>
        public string RfcReceptor
        {
            get
            {
                return this.rfcReceptorField;
            }
            set
            {
                this.rfcReceptorField = value;
                this.RaisePropertyChanged("RfcReceptor");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:advans-cfdi-cancelacion")]
    public partial class CancelarAutofirmaRequest : object, System.ComponentModel.INotifyPropertyChanged
    {
        
        private string rfcEmisorField;
        
        private string rfcReceptorField;
        
        private string uuidField;
        
        private double totalFacturaField;
        
        private string motivoField;
        
        private string folioSustitucionField;
        
        /// <remarks/>
        public string RfcEmisor
        {
            get
            {
                return this.rfcEmisorField;
            }
            set
            {
                this.rfcEmisorField = value;
                this.RaisePropertyChanged("RfcEmisor");
            }
        }
        
        /// <remarks/>
        public string RfcReceptor
        {
            get
            {
                return this.rfcReceptorField;
            }
            set
            {
                this.rfcReceptorField = value;
                this.RaisePropertyChanged("RfcReceptor");
            }
        }
        
        /// <remarks/>
        public string Uuid
        {
            get
            {
                return this.uuidField;
            }
            set
            {
                this.uuidField = value;
                this.RaisePropertyChanged("Uuid");
            }
        }
        
        /// <remarks/>
        public double TotalFactura
        {
            get
            {
                return this.totalFacturaField;
            }
            set
            {
                this.totalFacturaField = value;
                this.RaisePropertyChanged("TotalFactura");
            }
        }
        
        /// <remarks/>
        public string Motivo
        {
            get
            {
                return this.motivoField;
            }
            set
            {
                this.motivoField = value;
                this.RaisePropertyChanged("Motivo");
            }
        }
        
        /// <remarks/>
        public string FolioSustitucion
        {
            get
            {
                return this.folioSustitucionField;
            }
            set
            {
                this.folioSustitucionField = value;
                this.RaisePropertyChanged("FolioSustitucion");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:advans-cfdi-cancelacion")]
    public partial class ConsultarDocumentosRelacionadosResponse : object, System.ComponentModel.INotifyPropertyChanged
    {
        
        private int codeField;
        
        private string messageField;
        
        private string uuidPadreField;
        
        private string uuidHijoField;
        
        /// <remarks/>
        public int Code
        {
            get
            {
                return this.codeField;
            }
            set
            {
                this.codeField = value;
                this.RaisePropertyChanged("Code");
            }
        }
        
        /// <remarks/>
        public string Message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
                this.RaisePropertyChanged("Message");
            }
        }
        
        /// <remarks/>
        public string UuidPadre
        {
            get
            {
                return this.uuidPadreField;
            }
            set
            {
                this.uuidPadreField = value;
                this.RaisePropertyChanged("UuidPadre");
            }
        }
        
        /// <remarks/>
        public string UuidHijo
        {
            get
            {
                return this.uuidHijoField;
            }
            set
            {
                this.uuidHijoField = value;
                this.RaisePropertyChanged("UuidHijo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:advans-cfdi-cancelacion")]
    public partial class ConsultarDocumentosRelacionadosRequest : object, System.ComponentModel.INotifyPropertyChanged
    {
        
        private string privateKeyPemField;
        
        private string publicKeyPemField;
        
        private string uuidField;
        
        private string rfcEmisorField;
        
        private string rfcReceptorField;
        
        /// <remarks/>
        public string PrivateKeyPem
        {
            get
            {
                return this.privateKeyPemField;
            }
            set
            {
                this.privateKeyPemField = value;
                this.RaisePropertyChanged("PrivateKeyPem");
            }
        }
        
        /// <remarks/>
        public string PublicKeyPem
        {
            get
            {
                return this.publicKeyPemField;
            }
            set
            {
                this.publicKeyPemField = value;
                this.RaisePropertyChanged("PublicKeyPem");
            }
        }
        
        /// <remarks/>
        public string Uuid
        {
            get
            {
                return this.uuidField;
            }
            set
            {
                this.uuidField = value;
                this.RaisePropertyChanged("Uuid");
            }
        }
        
        /// <remarks/>
        public string RfcEmisor
        {
            get
            {
                return this.rfcEmisorField;
            }
            set
            {
                this.rfcEmisorField = value;
                this.RaisePropertyChanged("RfcEmisor");
            }
        }
        
        /// <remarks/>
        public string RfcReceptor
        {
            get
            {
                return this.rfcReceptorField;
            }
            set
            {
                this.rfcReceptorField = value;
                this.RaisePropertyChanged("RfcReceptor");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:advans-cfdi-cancelacion")]
    public partial class SimpleResponse : object, System.ComponentModel.INotifyPropertyChanged
    {
        
        private int codeField;
        
        private string messageField;
        
        private string detailField;
        
        /// <remarks/>
        public int Code
        {
            get
            {
                return this.codeField;
            }
            set
            {
                this.codeField = value;
                this.RaisePropertyChanged("Code");
            }
        }
        
        /// <remarks/>
        public string Message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
                this.RaisePropertyChanged("Message");
            }
        }
        
        /// <remarks/>
        public string Detail
        {
            get
            {
                return this.detailField;
            }
            set
            {
                this.detailField = value;
                this.RaisePropertyChanged("Detail");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:advans-cfdi-cancelacion")]
    public partial class AutorizarCancelacionAutofirmaRequest : object, System.ComponentModel.INotifyPropertyChanged
    {
        
        private string rfcField;
        
        private string uuidField;
        
        private string respuestaField;
        
        /// <remarks/>
        public string Rfc
        {
            get
            {
                return this.rfcField;
            }
            set
            {
                this.rfcField = value;
                this.RaisePropertyChanged("Rfc");
            }
        }
        
        /// <remarks/>
        public string Uuid
        {
            get
            {
                return this.uuidField;
            }
            set
            {
                this.uuidField = value;
                this.RaisePropertyChanged("Uuid");
            }
        }
        
        /// <remarks/>
        public string Respuesta
        {
            get
            {
                return this.respuestaField;
            }
            set
            {
                this.respuestaField = value;
                this.RaisePropertyChanged("Respuesta");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:advans-cfdi-cancelacion")]
    public partial class CancelarResponse : object, System.ComponentModel.INotifyPropertyChanged
    {
        
        private int codeField;
        
        private string messageField;
        
        private string idField;
        
        private string detailField;

        /// <remarks/>
        private string faultString;
        public string FaultString
        {
            get
            {
                return this.faultString;
            }
            set
            {
                this.faultString = value;
                this.RaisePropertyChanged("FaultString");
            }
        }
        public int Code
        {
            get
            {
                return this.codeField;
            }
            set
            {
                this.codeField = value;
                this.RaisePropertyChanged("Code");
            }
        }
        
        /// <remarks/>
        public string Message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
                this.RaisePropertyChanged("Message");
            }
        }
        
        /// <remarks/>
        public string Id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
                this.RaisePropertyChanged("Id");
            }
        }
        
        /// <remarks/>
        public string Detail
        {
            get
            {
                return this.detailField;
            }
            set
            {
                this.detailField = value;
                this.RaisePropertyChanged("Detail");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:advans-cfdi-cancelacion")]
    public partial class CancelarRequest : object, System.ComponentModel.INotifyPropertyChanged
    {
        
        private string privateKeyPemField;
        
        private string publicKeyPemField;
        
        private string uuidField;
        
        private string rfcReceptorField;
        
        private double totalField;
        
        private string motivoField;
        
        private string folioSustitucionField;
        
        /// <remarks/>
        public string PrivateKeyPem
        {
            get
            {
                return this.privateKeyPemField;
            }
            set
            {
                this.privateKeyPemField = value;
                this.RaisePropertyChanged("PrivateKeyPem");
            }
        }
        
        /// <remarks/>
        public string PublicKeyPem
        {
            get
            {
                return this.publicKeyPemField;
            }
            set
            {
                this.publicKeyPemField = value;
                this.RaisePropertyChanged("PublicKeyPem");
            }
        }
        
        /// <remarks/>
        public string Uuid
        {
            get
            {
                return this.uuidField;
            }
            set
            {
                this.uuidField = value;
                this.RaisePropertyChanged("Uuid");
            }
        }
        
        /// <remarks/>
        public string RfcReceptor
        {
            get
            {
                return this.rfcReceptorField;
            }
            set
            {
                this.rfcReceptorField = value;
                this.RaisePropertyChanged("RfcReceptor");
            }
        }
        
        /// <remarks/>
        public double Total
        {
            get
            {
                return this.totalField;
            }
            set
            {
                this.totalField = value;
                this.RaisePropertyChanged("Total");
            }
        }
        
        /// <remarks/>
        public string Motivo
        {
            get
            {
                return this.motivoField;
            }
            set
            {
                this.motivoField = value;
                this.RaisePropertyChanged("Motivo");
            }
        }
        
        /// <remarks/>
        public string FolioSustitucion
        {
            get
            {
                return this.folioSustitucionField;
            }
            set
            {
                this.folioSustitucionField = value;
                this.RaisePropertyChanged("FolioSustitucion");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:advans-cfdi-cancelacion")]
    public partial class ConsultarEstadoResponse : object, System.ComponentModel.INotifyPropertyChanged
    {
        
        private int codeField;
        
        private string messageField;
        
        private string detailField;
        
        private string acuseSATField;
        
        /// <remarks/>
        public int Code
        {
            get
            {
                return this.codeField;
            }
            set
            {
                this.codeField = value;
                this.RaisePropertyChanged("Code");
            }
        }
        
        /// <remarks/>
        public string Message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
                this.RaisePropertyChanged("Message");
            }
        }
        
        /// <remarks/>
        public string Detail
        {
            get
            {
                return this.detailField;
            }
            set
            {
                this.detailField = value;
                this.RaisePropertyChanged("Detail");
            }
        }
        
        /// <remarks/>
        public string AcuseSAT
        {
            get
            {
                return this.acuseSATField;
            }
            set
            {
                this.acuseSATField = value;
                this.RaisePropertyChanged("AcuseSAT");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public interface advanscfdicancelacionPortTypeChannel : CancearAdvansWS.advanscfdicancelacionPortType, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public partial class advanscfdicancelacionPortTypeClient : System.ServiceModel.ClientBase<CancearAdvansWS.advanscfdicancelacionPortType>, CancearAdvansWS.advanscfdicancelacionPortType
    {
        
        public advanscfdicancelacionPortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public CancearAdvansWS.ConsultarEstadoResponse ConsultarEstado(CancearAdvansWS.ConsultarEstadoRequest ConsultarEstadoRequest)
        {
            return base.Channel.ConsultarEstado(ConsultarEstadoRequest);
        }
        
        public System.Threading.Tasks.Task<CancearAdvansWS.ConsultarEstadoResponse> ConsultarEstadoAsync(CancearAdvansWS.ConsultarEstadoRequest ConsultarEstadoRequest)
        {
            return base.Channel.ConsultarEstadoAsync(ConsultarEstadoRequest);
        }
        
        public CancearAdvansWS.CancelarResponse Cancelar(CancearAdvansWS.CancelarRequest CancelarRequest)
        {
            return base.Channel.Cancelar(CancelarRequest);
        }
        
        public System.Threading.Tasks.Task<CancearAdvansWS.CancelarResponse> CancelarAsync(CancearAdvansWS.CancelarRequest CancelarRequest)
        {
            return base.Channel.CancelarAsync(CancelarRequest);
        }
        
        public CancearAdvansWS.SimpleResponse AutorizarCancelacionAutofirma(CancearAdvansWS.AutorizarCancelacionAutofirmaRequest AutorizarCancelacionAutofirmaRequest)
        {
            return base.Channel.AutorizarCancelacionAutofirma(AutorizarCancelacionAutofirmaRequest);
        }
        
        public System.Threading.Tasks.Task<CancearAdvansWS.SimpleResponse> AutorizarCancelacionAutofirmaAsync(CancearAdvansWS.AutorizarCancelacionAutofirmaRequest AutorizarCancelacionAutofirmaRequest)
        {
            return base.Channel.AutorizarCancelacionAutofirmaAsync(AutorizarCancelacionAutofirmaRequest);
        }
        
        public CancearAdvansWS.ConsultarDocumentosRelacionadosResponse ConsultarDocumentosRelacionados(CancearAdvansWS.ConsultarDocumentosRelacionadosRequest ConsultarDocumentosRelacionadosRequest)
        {
            return base.Channel.ConsultarDocumentosRelacionados(ConsultarDocumentosRelacionadosRequest);
        }
        
        public System.Threading.Tasks.Task<CancearAdvansWS.ConsultarDocumentosRelacionadosResponse> ConsultarDocumentosRelacionadosAsync(CancearAdvansWS.ConsultarDocumentosRelacionadosRequest ConsultarDocumentosRelacionadosRequest)
        {
            return base.Channel.ConsultarDocumentosRelacionadosAsync(ConsultarDocumentosRelacionadosRequest);
        }
        
        public CancearAdvansWS.CancelarResponse CancelarAutofirma(CancearAdvansWS.CancelarAutofirmaRequest CancelarAutofirmaRequest)
        {
            return base.Channel.CancelarAutofirma(CancelarAutofirmaRequest);
        }
        
        public System.Threading.Tasks.Task<CancearAdvansWS.CancelarResponse> CancelarAutofirmaAsync(CancearAdvansWS.CancelarAutofirmaRequest CancelarAutofirmaRequest)
        {
            return base.Channel.CancelarAutofirmaAsync(CancelarAutofirmaRequest);
        }
        
        public CancearAdvansWS.ConsultarDocumentosRelacionadosResponse ConsultarDocumentosRelacionadosAutofirma(CancearAdvansWS.ConsultarDocumentosRelacionadosAutofirmaRequest ConsultarDocumentosRelacionadosAutofirmaRequest)
        {
            return base.Channel.ConsultarDocumentosRelacionadosAutofirma(ConsultarDocumentosRelacionadosAutofirmaRequest);
        }
        
        public System.Threading.Tasks.Task<CancearAdvansWS.ConsultarDocumentosRelacionadosResponse> ConsultarDocumentosRelacionadosAutofirmaAsync(CancearAdvansWS.ConsultarDocumentosRelacionadosAutofirmaRequest ConsultarDocumentosRelacionadosAutofirmaRequest)
        {
            return base.Channel.ConsultarDocumentosRelacionadosAutofirmaAsync(ConsultarDocumentosRelacionadosAutofirmaRequest);
        }
        
        public CancearAdvansWS.ConsultarAutorizacionesPendientesResponse ConsultarAutorizacionesPendientesAutofirma(CancearAdvansWS.RFCEmisorRequest RFCEmisorRequest)
        {
            return base.Channel.ConsultarAutorizacionesPendientesAutofirma(RFCEmisorRequest);
        }
        
        public System.Threading.Tasks.Task<CancearAdvansWS.ConsultarAutorizacionesPendientesResponse> ConsultarAutorizacionesPendientesAutofirmaAsync(CancearAdvansWS.RFCEmisorRequest RFCEmisorRequest)
        {
            return base.Channel.ConsultarAutorizacionesPendientesAutofirmaAsync(RFCEmisorRequest);
        }
        
        public CancearAdvansWS.ConsultarEstadoSATResponse ConsultarEstadoSAT(CancearAdvansWS.ConsultarEstadoSATRequest ConsultarEstadoSATRequest)
        {
            return base.Channel.ConsultarEstadoSAT(ConsultarEstadoSATRequest);
        }
        
        public System.Threading.Tasks.Task<CancearAdvansWS.ConsultarEstadoSATResponse> ConsultarEstadoSATAsync(CancearAdvansWS.ConsultarEstadoSATRequest ConsultarEstadoSATRequest)
        {
            return base.Channel.ConsultarEstadoSATAsync(ConsultarEstadoSATRequest);
        }
        
        public CancearAdvansWS.ConsultarEstadoSolicitudResponse ConsultarEstadoSolicitud(CancearAdvansWS.ConsultarEstadoSolicitudRequest ConsultarEstadoSolicitudRequest)
        {
            return base.Channel.ConsultarEstadoSolicitud(ConsultarEstadoSolicitudRequest);
        }
        
        public System.Threading.Tasks.Task<CancearAdvansWS.ConsultarEstadoSolicitudResponse> ConsultarEstadoSolicitudAsync(CancearAdvansWS.ConsultarEstadoSolicitudRequest ConsultarEstadoSolicitudRequest)
        {
            return base.Channel.ConsultarEstadoSolicitudAsync(ConsultarEstadoSolicitudRequest);
        }
        
        public CancearAdvansWS.SimpleResponse AutorizarCancelacion(CancearAdvansWS.AutorizarCancelacionRequest AutorizarCancelacionRequest)
        {
            return base.Channel.AutorizarCancelacion(AutorizarCancelacionRequest);
        }
        
        public System.Threading.Tasks.Task<CancearAdvansWS.SimpleResponse> AutorizarCancelacionAsync(CancearAdvansWS.AutorizarCancelacionRequest AutorizarCancelacionRequest)
        {
            return base.Channel.AutorizarCancelacionAsync(AutorizarCancelacionRequest);
        }
        
        public CancearAdvansWS.ConsultarAutorizacionesPendientesResponse ConsultarAutorizacionesPendientes(CancearAdvansWS.SimpleKeysRequest SimpleKeysRequest)
        {
            return base.Channel.ConsultarAutorizacionesPendientes(SimpleKeysRequest);
        }
        
        public System.Threading.Tasks.Task<CancearAdvansWS.ConsultarAutorizacionesPendientesResponse> ConsultarAutorizacionesPendientesAsync(CancearAdvansWS.SimpleKeysRequest SimpleKeysRequest)
        {
            return base.Channel.ConsultarAutorizacionesPendientesAsync(SimpleKeysRequest);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
    }
}
