<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	<TargetFramework>net8.0</TargetFramework>
	<ImplicitUsings>enable</ImplicitUsings>
	<Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
	<Content Include="BL\Ventas\Timbrado\Connected Services\CancearAdvansWS\ConnectedService.json">
	  <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
	  <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
	</Content>
	<Content Include="Connected Services\AdvansTimbrado\ConnectedService.json">
	  <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
	  <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
	</Content>
  </ItemGroup>

  <ItemGroup>
	<PackageReference Include="Shared.Kalan" Version="2025.5.15.2340" />
	<PackageReference Include="Shared.Utilerias" Version="2025.2.15.1953" />
	  <PackageReference Include="System.ServiceModel.Duplex" Version="6.0.*" />
	  <PackageReference Include="System.ServiceModel.Federation" Version="8.1.1" />
	  <PackageReference Include="System.ServiceModel.NetTcp" Version="8.1.1" />
	  <PackageReference Include="System.ServiceModel.Security" Version="6.0.*" />
	  <PackageReference Include="Svg" Version="3.4.7" />
	  <PackageReference Include="Net.Codecrete.QrCodeGenerator" Version="2.0.6" />
	  <PackageReference Include="ReportViewerCore.NETCore" Version="15.1.26" />
	  <PackageReference Include="RestSharp" Version="112.1.0" />
	  <PackageReference Include="ChilkatDnCore" Version="10.1.2" />
	  <PackageReference Include="System.Text.RegularExpressions" Version="4.3.1" />
  </ItemGroup>
 
  <ItemGroup>
	<None Update="Reportes\Acuse.rdlc">
	  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	</None>
	<None Update="Reportes\Factura.rdlc">
	  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	</None>
  </ItemGroup>

</Project>
