sonar.projectKey=KalanBlazor
sonar.projectName=KalanBlazor
sonar.projectVersion=1.0
sonar.sources=.
sonar.language=cs
sonar.host.url=http://localhost:9000
sonar.login=sqa_46023af842e6ac348f959a20c83daf5bb759a48d